name: Page Tests
on: [push, pull_request]

jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./3060-Assignment-1/assignment 1 - 3060
      steps:
        - uses: actions/checkout@v4
          with:
            ref: test/page-structure-and-navigation
        - uses: actions/setup-node@v4
          with: 
            node-version: 20
        - run: npm install
        - run: npm test
